# Generated by Django 2.0.3 on 2019-01-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitterparse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.BigIntegerField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=255)),
            ],
        ),
    ]
