# Generated by Django 2.0.3 on 2019-01-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterparse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterparse',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='twitterparse',
            old_name='twitter_id',
            new_name='tweet_id',
        ),
        migrations.RemoveField(
            model_name='twitterparse',
            name='screen_name',
        ),
    ]
